mem = OnchipArray(dims=[100])
|\CL{A:}| for i in range(A,|\CK{par}|=2):
    |\CL{B:}| for j in range(B,|\CK{vec}|=16):
        addr1, data1 = ...
        mem(addr1) = data1 # W1
    |\CL{C:}| for k in range(C,|\CK{vec}|=16):
        addr2 = ...
        data2 = mem(addr2) # R1
        ...
