mem = OnchipArray(dims=[100])
|\CL{A:}| for i in range(A,|\CK{par}|=2):
    |\CL{B:}| for j in range(B,|\CK{vec}|=16):
        waddr, wdata = ...
        mem(waddr) = wdata # W1
    |\CL{C:}| for k in range(C,|\CK{vec}|=16):
        raddr = ...
        rdata = mem(raddr) # R1
        ...
