mem = array(dims=[100])
|\CL{A:}| for i in range(A):
    |\CL{B:}| for j in range(B):
        waddr, wdata = ...
        mem(waddr) = wdata # W1
    |\CL{C:}| for k in range(C):
        raddr = ...
        rdata = mem(raddr) # R1
        ...
